### ISSUE TITLE
请问杜绝 Bloomfilter 误判的原理是什么 ？

### ISSUE THREAD

**Issue by Cailiang** [rpcxio/basalt#6]
例如一个字符串   abc 通过一个 hash 算法算出来的 hash值是 123；另一个字符串  xyz 算出来的 hash 值是  123 + 2^32 他们的余数是一样的，由此产生误判，basalt 是怎么处理的呢？

**Comment by smallnest** [comment]
项目介绍有点标题党了，我会去掉。

## hash冲突问题

根据信息论理论，hash32计算出来的不可避免的会有冲突，所以无法保证原始字符串是否有冲突。

解决这个的办法可以参考比特币。比特币账号采用256bit的数据作为账号，理论上有冲突，实际上很难碰撞到，所以8个basalt可以用来处理hash256的数据，只存在理论上的数据冲突

## roaring vs. bloomfilter

两个应用于不同的场景。

roaring可以提供确定性的存在不存在， bloomfilter有误报的可能。
roaring可能比bloomfilter使用更多的存储
